language: csharp
solution: TestClass.sln
install:
  - nuget restore TestClass.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release TestClass.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./TestClass/bin/Release/TestClass.dll
  
notifications:
email:
recipients:
  - tuankiet234@gmail.com
  - ttkk.ben10@yahoo.com.vn
on_success: change
on_failure: always